/** Generate portable skill files from the maintained spec, protocol, and actual CLI help. */
export function buildSkillFiles(input: {
  subsetSpec: string;
  protocol: string;
  cliUsage: string;
  version: string;
}): Record<string, string> {
  const { subsetSpec, protocol, cliUsage, version } = input;
  const portable = (text: string) =>
    text.replace(
      /\]\(([-\w]+\.md)(#[^)]*)?\)/g,
      "](" + "https://github.com/ebi-oishii/beamer-editor/blob/main/docs/$1$2)",
    );
  const section = (text: string, start: string, end: string) => {
    const from = text.indexOf(start);
    const to = text.indexOf(end, from + start.length);
    if (from < 0 || to < 0) throw new Error(`生成元の節が見つかりません: ${start}`);
    return text.slice(from, to).trim();
  };
  const vocabulary = section(subsetSpec, "## 1. ファイル構造", "## 6. 将来拡張");
  const draft = protocol
    .split("## 付録: SKILL.md ドラフト")[1]
    ?.match(/```markdown\n([\s\S]*?)\n```/)?.[1];
  if (!draft) throw new Error("SKILL.md の生成元ドラフトが見つかりません");
  const banner = `<!-- Generated by pnpm build:skills; CLI ${version}. Do not edit. -->\n`;
  const skill = draft
    .replace(/\n---\n/, `\nmetadata:\n  cli-version: ${JSON.stringify(version)}\n---\n${banner}`)
    .replace("references/subset-cheatsheet.md", "[語彙・制約](references/subset-cheatsheet.md)")
    .replace("`deck snapshot --frame <addr>`", "`deck snapshot <file> --frame <addr>`");
  return {
    "SKILL.md": `${skill}\n\n利用可能なコマンドは [CLI リファレンス](references/cli.md)、依頼例は [指示パターン](examples/prompts.md)を参照。未提供のコマンドは実行せず、検証できなかった項目を報告する。\n`,
    "references/subset-cheatsheet.md": `${banner}# Beamer 語彙・制約\n\n語彙の唯一の生成元: docs/subset-spec.md。制約を落とさないよう関連節を収録する。ここにある仕様の一部は実装待ちであり、CLIの利用可能範囲は cli.md を参照。\n\n${portable(vocabulary)}\n`,
    "references/cli.md": `${banner}# CLI リファレンス\n\nCLI ${version} の実装済みコマンド（実際のヘルプから生成）:\n\n\`\`\`text\n${cliUsage.trim()}\n\`\`\`\n\nリポジトリ内では \`pnpm --filter @beamer-editor/cli deck <command> ...\` で実行する。\n\n終了コード: 0=成功・情報のみ、1=警告、2=lint error、3=操作失敗。JSONの成功結果はstdout、E_*エラーはstderr。\n\nsnapshot等、上の一覧に無いコマンドはこの版では未提供。PDF確認には \`deck export <file> --format pdf -o <pdf>\` を使い、実施できなかった検証を報告する。\n`,
    "examples/prompts.md": `${banner}${portable(section(protocol, "## 6. 人間側の指示パターン", "## 7. 微調整モード"))}\n`,
  };
}
