import { createHash } from "node:crypto";

export const SKILL_FINGERPRINT_PLACEHOLDER = "__BEAMER_DECK_SKILL_FINGERPRINT__";
export const SKILL_FILE_PATHS = [
  "SKILL.md",
  "references/subset-cheatsheet.md",
  "references/cli.md",
  "examples/prompts.md",
] as const;
export type SkillFilePath = (typeof SKILL_FILE_PATHS)[number];

/** Hash generated paths and contents. The SKILL metadata fingerprint is normalized to avoid a cycle. */
export function skillFingerprint(files: Record<SkillFilePath, string>): string {
  const hash = createHash("sha256");
  for (const path of [...SKILL_FILE_PATHS].sort()) {
    const content = files[path];
    if (content === undefined) throw new Error(`生成物が見つかりません: ${path}`);
    hash.update(path);
    hash.update("\0");
    hash.update(
      path === "SKILL.md"
        ? content.replace(
            /^ {2}fingerprint: "(?:[a-f0-9]{64}|__BEAMER_DECK_SKILL_FINGERPRINT__)"$/m,
            `  fingerprint: "${SKILL_FINGERPRINT_PLACEHOLDER}"`,
          )
        : content,
    );
    hash.update("\0");
  }
  return hash.digest("hex");
}

/** Generate portable skill files from the maintained spec, protocol, and actual CLI help. */
export function buildSkillFiles(input: {
  subsetSpec: string;
  protocol: string;
  cliUsage: string;
  version: string;
}): Record<SkillFilePath, string> {
  const { subsetSpec, protocol, cliUsage, version } = input;
  const portable = (text: string) =>
    text.replace(
      /\]\(([-\w]+\.md)(#[^)]*)?\)/g,
      "](" + "https://github.com/ebi-oishii/beamer-editor/blob/main/docs/$1$2)",
    );
  const section = (text: string, start: string, end: string) => {
    const from = text.indexOf(start);
    const to = text.indexOf(end, from + start.length);
    if (from < 0 || to < 0) throw new Error(`生成元の節が見つかりません: ${start}`);
    return text.slice(from, to).trim();
  };
  const vocabulary = section(subsetSpec, "## 1. ファイル構造", "## 6. 将来拡張");
  const principle = subsetSpec.match(/^大原則:.*$/m)?.[0];
  if (!principle) throw new Error("生成元の大原則が見つかりません");
  const draft = protocol
    .split("## 付録: SKILL.md ドラフト")[1]
    ?.match(/```markdown\n([\s\S]*?)\n```/)?.[1];
  if (!draft) throw new Error("SKILL.md の生成元ドラフトが見つかりません");
  const banner = `<!-- Generated by pnpm build:skills; CLI ${version}. Do not edit. -->\n`;
  const skill = draft.replace(
    /\n---\n/,
    `\nmetadata:\n  cli-version: ${JSON.stringify(version)}\n  fingerprint: ${JSON.stringify(SKILL_FINGERPRINT_PLACEHOLDER)}\n---\n${banner}`,
  );
  const promptTable = section(
    protocol,
    "| パターン | 指示の例 | エージェントの動き |",
    "## 7. 微調整モード",
  );
  const files: Record<SkillFilePath, string> = {
    "SKILL.md": `${skill}\n\n利用可能なコマンドは [CLI リファレンス](references/cli.md)、依頼例は [指示パターン](examples/prompts.md)を参照。CLI リファレンスにないコマンドは実行せず、検証できなかった項目を報告する。\n`,
    "references/subset-cheatsheet.md": `${banner}# Beamer 語彙・制約\n\n${principle}\n\n語彙の唯一の生成元: docs/subset-spec.md。CLI の利用可能範囲は cli.md を参照。\n\n${portable(vocabulary)}\n`,
    "references/cli.md": `${banner}# CLI リファレンス\n\nCLI ${version} の実装済みコマンド（実際のヘルプから生成）:\n\n\`\`\`text\n${cliUsage.trim()}\n\`\`\`\n\nリポジトリ内では \`pnpm --filter @beamer-editor/cli deck <command> ...\` で実行する。\n\n終了コード: 0=成功・情報のみ、1=警告、2=lint error、3=操作失敗。JSONの成功結果はstdout、E_*エラーはstderr。\n\n上の一覧にないコマンドはこの版では未提供。検証できない場合は、利用可能なコマンドで代替した内容と未実施項目を報告する。\n`,
    "examples/prompts.md": `${banner}# 依頼例\n\n自然言語で、対象と希望する変更を伝える。次の例を必要に応じて使う。\n\n${portable(promptTable)}\n`,
  };
  const fingerprint = skillFingerprint(files);
  return Object.fromEntries(
    Object.entries(files).map(([path, content]) => [
      path,
      content.replaceAll(SKILL_FINGERPRINT_PLACEHOLDER, fingerprint),
    ]),
  ) as Record<SkillFilePath, string>;
}
