import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { USAGE } from "../src/cli.ts";
import { buildSkillFiles } from "../src/skill-generator.ts";
import { CLI_VERSION } from "../src/version.ts";

const root = resolve(import.meta.dirname, "../../..");
const files = buildSkillFiles({
  subsetSpec: await readFile(resolve(root, "docs/subset-spec.md"), "utf8"),
  protocol: await readFile(resolve(root, "docs/ai-protocol.md"), "utf8"),
  cliUsage: USAGE,
  version: CLI_VERSION,
});
const fingerprint = files["SKILL.md"].match(/^ {2}fingerprint: "([a-f0-9]{64})"$/m)?.[1];
if (!fingerprint) throw new Error("生成した SKILL.md に fingerprint がありません");
const fingerprintSource =
  "// Generated by pnpm build:skills. Do not edit.\n" +
  `export const GENERATED_SKILL_FINGERPRINT =\n  ${JSON.stringify(fingerprint)};\n`;
const fingerprintPath = resolve(root, "packages/cli/src/generated-skill-fingerprint.ts");
if (process.argv.includes("--check")) {
  if ((await readFile(fingerprintPath, "utf8").catch(() => null)) !== fingerprintSource) {
    throw new Error(
      `生成済み fingerprint 定数が古いか存在しません: ${fingerprintPath} (pnpm build:skills)`,
    );
  }
} else {
  await writeFile(fingerprintPath, fingerprintSource);
}
for (const directory of ["skills/beamer-deck", ".claude/skills/beamer-deck"]) {
  for (const [name, content] of Object.entries(files)) {
    const path = resolve(root, directory, name);
    if (process.argv.includes("--check")) {
      if ((await readFile(path, "utf8").catch(() => null)) !== content) {
        throw new Error(`生成物が古いか存在しません: ${path} (pnpm build:skills)`);
      }
    } else {
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, content);
    }
  }
}
